baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Better mE'
theme = 'PaperMod'

[params]
  mainSections = ['posts']
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10